# Generated by Django 2.1.7 on 2019-04-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_nustartup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nustartup',
            name='team',
            field=models.TextField(default='insert', null=True),
        ),
    ]
