# Generated by Django 2.1.7 on 2019-04-19 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.CharField(default='All', max_length=255, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, default='default.jpg', upload_to='gallery/category')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='gallery/images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='enter', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gallery.Category'),
        ),
    ]
