# Generated by Django 2.1.7 on 2019-04-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190308_1842'),
        ('gallery', '0002_auto_20190420_0147'),
    ]

    operations = [
    ]
