# Generated by Django 2.1.7 on 2019-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_merge_20190424_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='gallery/images'),
        ),
    ]
