# Generated by Django 2.1.7 on 2019-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_member_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
