# Generated by Django 2.1.7 on 2019-03-07 18:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cuser',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
