# Generated by Django 2.1.7 on 2019-03-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190307_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuser',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
