# Generated by Django 2.1.7 on 2019-03-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190308_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='username',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
