# Generated by Django 2.1.7 on 2019-03-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='is_ciie',
            field=models.BooleanField(default=False),
        ),
    ]
