# Generated by Django 2.1.7 on 2019-04-07 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cuser_is_ciie'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cuser',
            managers=[
            ],
        ),
    ]
