# Generated by Django 2.1.7 on 2019-04-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190407_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='University',
        ),
        migrations.RemoveField(
            model_name='cuser',
            name='is_ciie',
        ),
    ]
