# Generated by Django 2.1.7 on 2019-04-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_no', models.CharField(max_length=30)),
                ('why_do_you_want_to_join_CIIE', models.TextField(null=True)),
                ('join_ciie', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_no', models.CharField(max_length=30)),
                ('why_do_you_want_to_join_CIIE', models.TextField()),
            ],
        ),
    ]
