# Generated by Django 2.1.7 on 2019-04-16 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='startup',
            fields=[
                ('name_of_enterprise', models.CharField(max_length=50)),
                ('name_of_enterpreneur', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('nationality', models.CharField(default='', max_length=50)),
                ('dob', models.CharField(default='', max_length=50)),
                ('address', models.TextField(default='', verbose_name='permanent address')),
                ('education', models.CharField(default='#', max_length=20)),
                ('website', models.CharField(blank=True, default='', max_length=300, validators=[django.core.validators.URLValidator()])),
                ('organization_type', models.CharField(choices=[('n', 'Not for Profit Organization'), ('p', 'For Profit Organization')], default='', max_length=30)),
                ('is_your_enterprise', models.CharField(choices=[('r', 'Registered'), ('n', 'Not Registered')], default='', max_length=30)),
                ('impact', models.CharField(choices=[('d', 'Direct'), ('i', 'Indirect')], default='', max_length=30, verbose_name='type of impact on social sector')),
                ('nu_mentor', models.BooleanField(default=False, verbose_name='Have a mentor from NU ?')),
                ('name_of_mentor', models.CharField(blank=True, default='', max_length=50)),
                ('sector', models.CharField(choices=[('ai', 'Information, Communication and Entertainment'), ('bi', 'Food, Agriculture and allied sectors'), ('ci', 'Augmented Reality , Big data and analytics , Image Processing and Recognition ,Cloud computing, Cyber Security'), ('di', 'Renewable energy sources , Green Technology'), ('ei', 'Bio Informatics'), ('fi', 'Financial Technology, NPD , Services'), ('gi', 'Other Contemporary area')], default='', max_length=300, verbose_name='sector for your enterprise')),
                ('mention', models.CharField(blank=True, default='', max_length=40, verbose_name='Mention your sector if not mentioned above')),
                ('infra_resource', models.TextField(default='', verbose_name='What all infrastructural resources you require ? Mention them clearly')),
                ('special_req', models.TextField(blank=True, default='', verbose_name='Mention any special requirement')),
                ('pro_req', models.TextField(blank=True, verbose_name='Mention requirements of professional services/support if needed')),
                ('employee_space', models.TextField(default='', verbose_name='Mention number of employees occupying the space')),
                ('current_space', models.TextField(blank=True, default='', verbose_name='Are you currently occupying a space ? If yes give details such as area, location and monthly cost')),
                ('descr', models.TextField(default='', verbose_name='Description of your business products/services')),
                ('descr_bplan', models.TextField(default='', verbose_name='Description of your b plan and attach a copy of the same')),
                ('attachment_of_bplan', models.FileField(blank=True, upload_to='')),
                ('sourc_fund', models.TextField(blank=True, default='', verbose_name='Specify sources of funds')),
                ('benefic', models.TextField(default='', verbose_name='Who will benefit from your product/Service')),
                ('stp_benefit', models.TextField(default='', verbose_name='How will your startup be benefitted from incubating at NU')),
                ('if_select', models.TextField(default='', verbose_name='If selected , when will you start the incubation facility ?')),
                ('other_de', models.TextField(blank=True, default='', verbose_name='Any other details you want to give which will help evaluating your proposal ? ')),
                ('Signature', models.FileField(default='#', upload_to='')),
            ],
        ),
    ]
