# Generated by Django 2.1.7 on 2019-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_startup'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='idea',
            field=models.TextField(default='nill', max_length=4095),
        ),
        migrations.AlterField(
            model_name='idea',
            name='why_do_you_want_to_join_CIIE',
            field=models.TextField(max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='join',
            name='why_do_you_want_to_join_CIIE',
            field=models.TextField(max_length=4095),
        ),
    ]
