# Generated by Django 2.1.7 on 2019-04-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_auto_20190417_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='idea',
            field=models.TextField(max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='why_do_you_want_to_join_CIIE',
            field=models.TextField(blank=True, max_length=4095, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='education',
            field=models.CharField(default='', max_length=20),
        ),
    ]
